export { default as ArrowRight } from "./ArrowRight";
export { default as ArrowTop } from "./ArrowTop";
export { default as Burger } from "./Burger";
export { default as Close } from "./Close";
export { default as Instagram } from "./Instagram";
export { default as Pinterest } from "./Pinterest";
export { default as Prev } from "./Prev";
export { default as Next } from "./Next";
export { default as Search } from "./Search";
